# name: Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#         with:
#           driver: docker-container
#           buildkitd-flags: --debug

#       - name: Cache pnpm store
#         uses: actions/cache@v3
#         with:
#           path: ~/.pnpm-store
#           key: "${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}"
#           restore-keys: |
#             ${{ runner.os }}-pnpm-

#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.CR_PAT }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: true
#           cache-from: type=gha,scope=kromka-ecom
#           cache-to: type=gha,scope=kromka-ecom,mode=max
#           tags: ghcr.io/romandenysov/kromka-ecom:prod
#           build-args: |
#             DATABASE_URL=${{ secrets.DATABASE_URL }}
#             PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}
#             AUTH_SECRET=${{ secrets.AUTH_SECRET }}
#             AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }}
#             AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }}
#             EMAIL_SERVER=${{ secrets.EMAIL_SERVER }}
#             EMAIL_FROM=${{ secrets.EMAIL_FROM }}
#             EMAIL_HOST=${{ secrets.EMAIL_HOST }}
#             EMAIL_PASS=${{ secrets.EMAIL_PASS }}
#             STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
#             NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }}
#             NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}
#             NEXT_PUBLIC_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_MAPS_API_KEY }}
